# Generated by Django 5.2.15 on 2026-07-08 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_user_organization"),
        ("organizations", "0004_organization_onboarding_completed_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "ordering": ["-date_joined"],
                "verbose_name": "Usuario",
                "verbose_name_plural": "Usuarios",
            },
        ),
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
        migrations.AddField(
            model_name="user",
            name="must_change_password",
            field=models.BooleanField(
                default=True, verbose_name="Forzar cambio de contraseña"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="two_factor_backup_codes",
            field=models.JSONField(
                blank=True, default=list, verbose_name="Códigos de respaldo 2FA"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="two_factor_enabled",
            field=models.BooleanField(default=False, verbose_name="2FA Activo"),
        ),
        migrations.AddField(
            model_name="user",
            name="two_factor_secret",
            field=models.CharField(
                blank=True, max_length=32, null=True, verbose_name="Secreto 2FA"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                max_length=254, unique=True, verbose_name="Correo electrónico"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="institutional_id",
            field=models.CharField(
                help_text="Código único (Ej: ADMIN-TECSUP, 20210001)",
                max_length=30,
                unique=True,
                verbose_name="ID Institucional",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_verified",
            field=models.BooleanField(default=False, verbose_name="Email verificado"),
        ),
        migrations.AlterField(
            model_name="user",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="users",
                to="organizations.organization",
                verbose_name="Organización",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("STUDENT", "Estudiante"),
                    ("TEACHER", "Docente"),
                    ("ADMIN", "Administrador"),
                    ("ELECTORAL_COMMISSION", "Comisión Electoral"),
                    ("OBSERVER", "Observador"),
                ],
                default="STUDENT",
                max_length=40,
                verbose_name="Rol",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                max_length=150, unique=True, verbose_name="Nombre de usuario"
            ),
        ),
    ]
