# Generated by Django 5.2.15 on 2026-07-05 03:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("elections", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OneTimeToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token", models.CharField(max_length=128, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                (
                    "election",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ottokens",
                        to="elections.election",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ottokens",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("LOGIN", "Inicio de sesión"),
                            ("VERIFY_2FA", "Verificación 2FA"),
                            ("CREATE_ELECTION", "Crear elección"),
                            ("OPEN_ELECTION", "Abrir elección"),
                            ("CAST_VOTE", "Emitir voto"),
                            ("CLOSE_ELECTION", "Cerrar elección"),
                            ("CERTIFY_RESULT", "Certificar resultado"),
                            ("PUBLISH_RESULT", "Publicar resultado"),
                        ],
                        max_length=40,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("signature", models.CharField(blank=True, max_length=256)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "election",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="elections.election",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["action", "timestamp"],
                        name="security_au_action_85f886_idx",
                    ),
                    models.Index(
                        fields=["election", "timestamp"],
                        name="security_au_electio_a7495b_idx",
                    ),
                ],
            },
        ),
    ]
