# Generated by Django 5.2.15 on 2026-07-05 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("security", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="auditlog",
            name="current_hash",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="auditlog",
            name="previous_hash",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("LOGIN", "Login"),
                    ("VERIFY_2FA", "Verify 2FA"),
                    ("CREATE_ELECTION", "Create election"),
                    ("OPEN_ELECTION", "Open election"),
                    ("CAST_VOTE", "Cast vote"),
                    ("CLOSE_ELECTION", "Close election"),
                    ("CERTIFY_RESULT", "Certify result"),
                    ("PUBLISH_RESULT", "Publish result"),
                ],
                max_length=40,
            ),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="signature",
            field=models.TextField(blank=True, default=""),
        ),
    ]
