# Generated by Django 5.2.15 on 2026-07-05 03:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("elections", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ballot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.PositiveIntegerField(default=1)),
                ("is_active", models.BooleanField(default=True)),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "election",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ballots",
                        to="elections.election",
                    ),
                ),
            ],
            options={
                "unique_together": {("election", "version")},
            },
        ),
        migrations.CreateModel(
            name="BallotPosition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveSmallIntegerField(default=1)),
                (
                    "ballot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ballot_positions",
                        to="ballots.ballot",
                    ),
                ),
                (
                    "position",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ballot_positions",
                        to="elections.position",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
                "unique_together": {("ballot", "position")},
            },
        ),
        migrations.CreateModel(
            name="BallotOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "option_type",
                    models.CharField(
                        choices=[
                            ("CANDIDATE_LIST", "Lista"),
                            ("BLANK", "Blanco"),
                            ("NULL", "Nulo"),
                        ],
                        default="CANDIDATE_LIST",
                        max_length=20,
                    ),
                ),
                ("label", models.CharField(max_length=120)),
                (
                    "candidate_list",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="elections.candidatelist",
                    ),
                ),
                (
                    "ballot_position",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="ballots.ballotposition",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("ballot_position", "candidate_list"),
                        name="unique_candidate_list_per_ballot_position",
                    )
                ],
            },
        ),
    ]
