# Generated by Django 5.2.15 on 2026-07-05 03:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academic", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Election",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "election_type",
                    models.CharField(
                        choices=[
                            ("UNIVERSITY", "Universitaria"),
                            ("FACULTY", "Facultad"),
                            ("PROGRAM", "Carrera/Programa"),
                        ],
                        max_length=20,
                    ),
                ),
                ("start_at", models.DateTimeField()),
                ("end_at", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Borrador"),
                            ("SCHEDULED", "Programada"),
                            ("OPEN", "Abierta"),
                            ("CLOSED", "Cerrada"),
                            ("CERTIFIED", "Certificada"),
                            ("PUBLISHED", "Publicada"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_elections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "faculty",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="elections",
                        to="academic.faculty",
                    ),
                ),
                (
                    "period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="elections",
                        to="academic.academicperiod",
                    ),
                ),
                (
                    "program",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="elections",
                        to="academic.program",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CandidateList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("acronym", models.CharField(blank=True, max_length=20)),
                ("motto", models.CharField(blank=True, max_length=255)),
                (
                    "logo",
                    models.ImageField(blank=True, null=True, upload_to="lists/logos/"),
                ),
                (
                    "election",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="candidate_lists",
                        to="elections.election",
                    ),
                ),
            ],
            options={
                "unique_together": {("election", "name")},
            },
        ),
        migrations.CreateModel(
            name="ElectionRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "min_turnout_percentage",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("allow_blank_vote", models.BooleanField(default=True)),
                ("allow_null_vote", models.BooleanField(default=True)),
                (
                    "max_positions_per_ballot",
                    models.PositiveSmallIntegerField(default=1),
                ),
                ("requires_2fa", models.BooleanField(default=True)),
                (
                    "election",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rules",
                        to="elections.election",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Position",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("description", models.TextField(blank=True)),
                ("seats", models.PositiveSmallIntegerField(default=1)),
                (
                    "election",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="positions",
                        to="elections.election",
                    ),
                ),
            ],
            options={
                "unique_together": {("election", "name")},
            },
        ),
        migrations.CreateModel(
            name="Candidacy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveSmallIntegerField(default=1)),
                ("is_principal", models.BooleanField(default=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="candidacies",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "candidate_list",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="candidacies",
                        to="elections.candidatelist",
                    ),
                ),
                (
                    "position",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="candidacies",
                        to="elections.position",
                    ),
                ),
            ],
            options={
                "ordering": ["position", "order"],
                "unique_together": {("position", "user")},
            },
        ),
    ]
