# Generated by Django 5.2.15 on 2026-07-11 14:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("elections", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="election",
            name="form_structure",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="election",
            name="is_anonymous_allowed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="election",
            name="process_type",
            field=models.CharField(
                choices=[
                    ("VOTE", "Votación Política / Cargos"),
                    ("FAIR", "Concurso / Feria de Proyectos"),
                    ("FEEDBACK", "Evaluación / Estrellas / Ponencias"),
                    ("FORM", "Formulario / Denuncia Anónima / Encuesta"),
                ],
                default="VOTE",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="candidacy",
            name="position",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="candidacies",
                to="elections.position",
            ),
        ),
        migrations.CreateModel(
            name="VoteRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ballot_data", models.JSONField()),
                (
                    "digital_signature",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "election",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="form_responses",
                        to="elections.election",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
