# Generated by Django 5.2.15 on 2026-07-06 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="country",
            field=models.CharField(default="Perú", max_length=100),
        ),
        migrations.AddField(
            model_name="organization",
            name="logo",
            field=models.ImageField(
                blank=True, null=True, upload_to="organizations/logos/"
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="primary_color",
            field=models.CharField(default="#0066CC", max_length=7),
        ),
        migrations.AddField(
            model_name="organization",
            name="secondary_color",
            field=models.CharField(default="#FFD700", max_length=7),
        ),
        migrations.AddField(
            model_name="organization",
            name="timezone",
            field=models.CharField(default="America/Lima", max_length=50),
        ),
        migrations.AlterField(
            model_name="organization",
            name="org_type",
            field=models.CharField(
                choices=[
                    ("UNIVERSITY", "Universidad"),
                    ("INSTITUTE", "Instituto"),
                    ("SCHOOL", "Escuela/Colegio"),
                    ("COMPANY", "Empresa"),
                    ("ASSOCIATION", "Asociación"),
                    ("OTHER", "Otro"),
                ],
                default="UNIVERSITY",
                max_length=20,
            ),
        ),
    ]
