# Generated by Django 5.2.15 on 2026-07-08 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0003_organizationrequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="onboarding_completed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="organization",
            name="onboarding_completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
